name: 'Terraform Apply Workflow'

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: 'Terraform Linter'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        terraform-versions: [latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix['terraform-versions'] }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -list=true -diff -check -recursive

  apply:
    name: 'Terraform Apply'
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
        terraform-versions: [latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws-us-gov:iam::012345678901:role/github-oidc-terraform-role
        aws-region: us-gov-west-1

    - name: Test AWS Credentials
      run: aws sts get-caller-identity

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix['terraform-versions'] }}

    - name: Terraform Init
      id: init
      run: terraform init -no-color

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color -auto-approve
